# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\minsu\OneDrive\바탕 화면\Youtube_Stream\Lesson 3\ClockGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 190)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber_year = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_year.setObjectName("lcdNumber_year")
        self.horizontalLayout.addWidget(self.lcdNumber_year)
        self.lcdNumber_month = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_month.setObjectName("lcdNumber_month")
        self.horizontalLayout.addWidget(self.lcdNumber_month)
        self.lcdNumber_date = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_date.setObjectName("lcdNumber_date")
        self.horizontalLayout.addWidget(self.lcdNumber_date)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcdNumber_hour = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_hour.setObjectName("lcdNumber_hour")
        self.horizontalLayout_2.addWidget(self.lcdNumber_hour)
        self.lcdNumber_min = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_min.setObjectName("lcdNumber_min")
        self.horizontalLayout_2.addWidget(self.lcdNumber_min)
        self.lcdNumber_sec = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_sec.setObjectName("lcdNumber_sec")
        self.horizontalLayout_2.addWidget(self.lcdNumber_sec)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
